// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SecuresCompany.Persistence.Context;

#nullable disable

namespace SecuresCompany.Persistence.Migrations
{
    [DbContext(typeof(SecureCompanyContext))]
    [Migration("20260322190255_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SecuresCompany.Domain.Entities.CertificacionesEmpleado", b =>
                {
                    b.Property<int>("CertificacionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CertificacionID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CertificacionId"));

                    b.Property<int>("EmpleadoId")
                        .HasColumnType("int")
                        .HasColumnName("EmpleadoID");

                    b.Property<DateOnly?>("FechaObtencion")
                        .HasColumnType("date");

                    b.Property<string>("NombreCertificacion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CertificacionId");

                    b.HasIndex(new[] { "EmpleadoId" }, "IX_CertificacionesEmpleado_Empleado");

                    b.ToTable("CertificacionesEmpleado", (string)null);
                });

            modelBuilder.Entity("SecuresCompany.Domain.Entities.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("clienteId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("AprobacionPendiente")
                        .HasColumnType("bit")
                        .HasColumnName("aprobacionPendiente");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("DescuentoFidelidad")
                        .HasColumnType("decimal(5, 2)")
                        .HasColumnName("descuentoFidelidad");

                    b.Property<int?>("DiasMora")
                        .HasColumnType("int")
                        .HasColumnName("diasMora");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("email");

                    b.Property<int?>("EmpleadoAsignadoId")
                        .HasColumnType("int")
                        .HasColumnName("empleadoAsignadoID");

                    b.Property<bool?>("EnProcesoCobro")
                        .HasColumnType("bit")
                        .HasColumnName("enProcesoCobro");

                    b.Property<DateTime>("FechaIngreso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("fechaIngreso")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateOnly?>("FechaProximaRevision")
                        .HasColumnType("date")
                        .HasColumnName("fechaProximaRevision");

                    b.Property<DateOnly?>("FechaUltimoAtraso")
                        .HasColumnType("date")
                        .HasColumnName("fechaUltimoAtraso");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("MesesConsecutivosAlDia")
                        .HasColumnType("int")
                        .HasColumnName("mesesConsecutivosAlDia");

                    b.Property<decimal?>("MontoMora")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("montoMora");

                    b.Property<string>("MotivoMora")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("motivoMora");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nombreCliente");

                    b.Property<string>("NumeroPoliza")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("numeroPoliza");

                    b.Property<int?>("PorcentajeCompletado")
                        .HasColumnType("int")
                        .HasColumnName("porcentajeCompletado");

                    b.Property<decimal?>("RecargoPorMora")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("recargoPorMora");

                    b.Property<decimal>("SaldoPendiente")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("saldoPendiente");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("telefono");

                    b.Property<string>("TipoCliente")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("tipoCliente");

                    b.Property<string>("TipoSeguro")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("tipoSeguro");

                    b.Property<DateOnly?>("UltimoPago")
                        .HasColumnType("date")
                        .HasColumnName("ultimoPago");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("VerificacionCompletada")
                        .HasColumnType("bit")
                        .HasColumnName("verificacionCompletada");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "EmpleadoAsignadoId" }, "IX_Clients_empleadoAsignado");

                    b.HasIndex(new[] { "NumeroPoliza" }, "IX_Clients_numeroPoliza");

                    b.HasIndex(new[] { "TipoCliente" }, "IX_Clients_tipoCliente");

                    b.HasIndex(new[] { "Email" }, "UQ_Clients_email")
                        .IsUnique()
                        .HasFilter("[email] IS NOT NULL");

                    b.HasIndex(new[] { "NumeroPoliza" }, "UQ_Clients_numeroPoliza")
                        .IsUnique();

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("SecuresCompany.Domain.Entities.DocumentosPendiente", b =>
                {
                    b.Property<int>("DocumentoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("documentoID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DocumentoId"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("int")
                        .HasColumnName("clienteID");

                    b.Property<string>("NombreDocumento")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nombreDocumento");

                    b.HasKey("DocumentoId");

                    b.HasIndex(new[] { "ClienteId" }, "IX_DocumentosPendientes_cliente");

                    b.ToTable("DocumentosPendientes");
                });

            modelBuilder.Entity("SecuresCompany.Domain.Entities.Empleado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AreaEspecializacion")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("areaEspecializacion");

                    b.Property<decimal?>("BonoGerencial")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("bonoGerencial");

                    b.Property<decimal?>("BonoGestion")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("bonoGestion");

                    b.Property<decimal?>("BonoTecnico")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("bonoTecnico");

                    b.Property<int?>("ContratacionesMes")
                        .HasColumnType("int")
                        .HasColumnName("contratacionesMes");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Departamento")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("departamento");

                    b.Property<int?>("DepartamentosSupervisa")
                        .HasColumnType("int")
                        .HasColumnName("departamentosSupervisa");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EmpleadosAcargo")
                        .HasColumnType("int")
                        .HasColumnName("empleadosAcargo");

                    b.Property<int?>("EquipoDesarrollo")
                        .HasColumnType("int")
                        .HasColumnName("equipoDesarrollo");

                    b.Property<string>("EspecialidadRrhh")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("especialidadRRHH");

                    b.Property<int?>("GerenteId")
                        .HasColumnType("int")
                        .HasColumnName("gerenteID");

                    b.Property<string>("IdEmpleado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("idEmpleado");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("LineasCodigoMes")
                        .HasColumnType("int")
                        .HasColumnName("lineasCodigoMes");

                    b.Property<string>("NivelExperiencia")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("nivelExperiencia");

                    b.Property<string>("NivelTecnico")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("nivelTecnico");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nombre");

                    b.Property<int?>("NumeroSubordinados")
                        .HasColumnType("int")
                        .HasColumnName("numeroSubordinados");

                    b.Property<decimal?>("PresupuestoAnual")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("presupuestoAnual");

                    b.Property<int?>("ProyectosAsignados")
                        .HasColumnType("int")
                        .HasColumnName("proyectosAsignados");

                    b.Property<int?>("ProyectosTi")
                        .HasColumnType("int")
                        .HasColumnName("proyectosTI");

                    b.Property<string>("Puesto")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("puesto");

                    b.Property<decimal>("SalarioBase")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("salarioBase");

                    b.Property<int?>("TareasPendientes")
                        .HasColumnType("int")
                        .HasColumnName("tareasPendientes");

                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("VacantesActivas")
                        .HasColumnType("int")
                        .HasColumnName("vacantesActivas");

                    b.Property<DateTime>("fechaIngreso")
                        .HasColumnType("datetime2")
                        .HasColumnName("fechaIngreso");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Departamento" }, "IX_Empleados_Departamento");

                    b.HasIndex(new[] { "GerenteId" }, "IX_Empleados_Gerente");

                    b.HasIndex(new[] { "IdEmpleado" }, "IX_Empleados_IdEmpleado");

                    b.HasIndex(new[] { "Puesto" }, "IX_Empleados_Puesto");

                    b.HasIndex(new[] { "IdEmpleado" }, "UQ_Empleados_IdEmpleado")
                        .IsUnique();

                    b.ToTable("Empleados");
                });

            modelBuilder.Entity("SecuresCompany.Domain.Entities.LenguajesProgramacionEmpleado", b =>
                {
                    b.Property<int>("LenguajeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("LenguajeID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LenguajeId"));

                    b.Property<int>("EmpleadoId")
                        .HasColumnType("int")
                        .HasColumnName("EmpleadoID");

                    b.Property<string>("NivelDominio")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("NombreLenguaje")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("LenguajeId");

                    b.HasIndex(new[] { "EmpleadoId" }, "IX_LenguajesProgramacionEmpleado_Empleado");

                    b.ToTable("LenguajesProgramacionEmpleado", (string)null);
                });

            modelBuilder.Entity("SecuresCompany.Domain.Entities.CertificacionesEmpleado", b =>
                {
                    b.HasOne("SecuresCompany.Domain.Entities.Empleado", "Empleado")
                        .WithMany("CertificacionesEmpleados")
                        .HasForeignKey("EmpleadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_CertificacionesEmpleado_Empleado");

                    b.Navigation("Empleado");
                });

            modelBuilder.Entity("SecuresCompany.Domain.Entities.Client", b =>
                {
                    b.HasOne("SecuresCompany.Domain.Entities.Empleado", "EmpleadoAsignado")
                        .WithMany("Clients")
                        .HasForeignKey("EmpleadoAsignadoId")
                        .HasConstraintName("FK_Clientes_EmpleadoAsignado");

                    b.Navigation("EmpleadoAsignado");
                });

            modelBuilder.Entity("SecuresCompany.Domain.Entities.DocumentosPendiente", b =>
                {
                    b.HasOne("SecuresCompany.Domain.Entities.Client", "Cliente")
                        .WithMany("DocumentosPendientes")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_DocumentosPendientes_cliente");

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("SecuresCompany.Domain.Entities.Empleado", b =>
                {
                    b.HasOne("SecuresCompany.Domain.Entities.Empleado", "Gerente")
                        .WithMany("InverseGerente")
                        .HasForeignKey("GerenteId")
                        .HasConstraintName("FK_Empleados_Gerente");

                    b.Navigation("Gerente");
                });

            modelBuilder.Entity("SecuresCompany.Domain.Entities.LenguajesProgramacionEmpleado", b =>
                {
                    b.HasOne("SecuresCompany.Domain.Entities.Empleado", "Empleado")
                        .WithMany("LenguajesProgramacionEmpleados")
                        .HasForeignKey("EmpleadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_LenguajesProgramacionEmpleado_Empleado");

                    b.Navigation("Empleado");
                });

            modelBuilder.Entity("SecuresCompany.Domain.Entities.Client", b =>
                {
                    b.Navigation("DocumentosPendientes");
                });

            modelBuilder.Entity("SecuresCompany.Domain.Entities.Empleado", b =>
                {
                    b.Navigation("CertificacionesEmpleados");

                    b.Navigation("Clients");

                    b.Navigation("InverseGerente");

                    b.Navigation("LenguajesProgramacionEmpleados");
                });
#pragma warning restore 612, 618
        }
    }
}
